stages:
  scrape-data:
    cmd: python urban_renewal/scrape_urban_renewal_locations.py
    deps:
    - urban_renewal/scrape_urban_renewal_locations.py
    outs:
    - data/raw/urban_renewal_location_photos.csv:
        persist: true
  create_address_ner_training_data:
    cmd: python urban_renewal/create_address_ner_trainset.py 5000 500 500 692025
    deps:
    - urban_renewal/create_address_ner_trainset.py
    - data/raw/urban_renewal_location_photos.csv
    outs:
    - data/processed/address_ner/eval.spacy
    - data/processed/address_ner/test.spacy
    - data/processed/address_ner/train.spacy
    - data/interim/urban_renewal_locations_v1.csv
  train_address_ner:
    cmd: python -m spacy train models/address_ner/config.cfg --paths.train 
      data/processed/address_ner/train.spacy --paths.dev 
      data/processed/address_ner/eval.spacy --output ./models/address_ner
    deps:
    - data/processed/address_ner/eval.spacy
    - data/processed/address_ner/train.spacy
    - models/address_ner/config.cfg
    outs:
    - models/address_ner/model-last
    - models/address_ner/model-best
  test_address_ner:
    cmd: python -m spacy evaluate models/address_ner/model-best 
      data/processed/address_ner/test.spacy --output 
      models/address_ner/metrics_test.json
    deps:
    - data/processed/address_ner/test.spacy
    - models/address_ner/model-best
    outs:
    - models/address_ner/metrics_test.json
  nlp_extract_addresses:
    cmd: python urban_renewal/nlp_extract_addresses.py title_cleaned 
      street_address
    deps:
    - data/interim/urban_renewal_locations_v1.csv
    - models/address_ner/model-best
    outs:
    - data/interim/urban_renewal_locations_v2.csv
  regex_extract_addresses:
    cmd: python urban_renewal/regex_extract_addresses.py title_cleaned 
      street_address
    deps:
    - data/interim/urban_renewal_locations_v2.csv
    outs:
    - data/interim/urban_renewal_locations_v3.csv
  geocode_addresses:
    cmd: python urban_renewal/geocode_addresses.py
    deps:
    - data/interim/urban_renewal_locations_v4.csv
    - urban_renewal/geocode_addresses.py
    outs:
    - data/interim/urban_renewal_locations_v5.csv
    - data/interim/urban_renewal_addresses_v1.geojson
    - data/interim/unmatched_addresses.csv

  create_figures:
    cmd: python urban_renewal/create_figures.py
    deps:
    - data/external/City_Boundary_20250624.geojson
    - data/interim/urban_renewal_addresses_v1.geojson
    - data/interim/urban_renewal_locations_v5.csv
    - urban_renewal/create_figures.py
    outs:
    - reports/figures/urban_renewal_locations_by_time_period.png:
        cache: false
    - docs/urban_renewal_projects.html:
        cache: false
