stages:
  scrape-data:
    cmd: python urban_renewal/scrape_urban_renewal_locations.py
    deps:
    - urban_renewal/scrape_urban_renewal_locations.py
    outs:
    - data/raw/urban_renewal_location_photos.csv
  create_address_ner_training_data:
    cmd: python urban_renewal/create_address_ner_trainset.py 2000 200 200 692025
    deps:
    - urban_renewal/create_address_ner_trainset.py
    - data/raw/urban_renewal_location_photos.csv
    outs:
    - data/processed/address_ner/eval.spacy
    - data/processed/address_ner/test.spacy
    - data/processed/address_ner/train.spacy
    - data/interim/urban_renewal_locations_v1.csv

  train_address_ner:
    cmd: python -m spacy train models/address_ner/config.cfg --paths.train 
      data/processed/address_ner/train.spacy --paths.dev 
      data/processed/address_ner/eval.spacy --output ./models/address_ner
    deps:
    - data/processed/address_ner/eval.spacy
    - data/processed/address_ner/train.spacy
    - models/address_ner/config.cfg
    outs:
    - models/address_ner/model-last
    - models/address_ner/model_best
